services:
  mysql:
    image: mysql:9.0.1
    environment: #variaveis de ambiente do container
      MYSQL_ROOT_PASSWORD: ${ENV_ROOT_PASSWORD}
      MYSQL_USER: ${ENV_MYSQL_USER}
      MYSQL_PASSWORD: ${ENV_MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - branches-db:/var/lib/mysql
volumes:
  branches-db: