spring:
  config:
    import: optional:classpath:.env[.properties]
  datasource:
    url: jdbc:mysql://localhost:3307/anime_service?useTimezone=true&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: ${ENV_ROOT_USER}
    password: ${ENV_ROOT_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  application:
    name: anime-service
  threads:
    virtual:
      enabled: true
server:
  servlet:
    context-path: / #default
  error:
    include-stacktrace: on_param
  tomcat:
    threads: #threads de plataforma
      max: 20 #padrão é 200 -> diminuindo o numero de threads e habilitando as virtuals aumenta muito a performace com menos memoria
logging:
  level:
    academy.devdojo: debug